# Generated by Django 6.1.1 on 2026-09-07 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilInvestidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('classificacao', models.CharField(blank=True, choices=[('CONSERVADOR', 'Conservador'), ('MODERADO', 'Moderado'), ('ARROJADO', 'Arrojado')], max_length=20)),
                ('objetivo', models.CharField(blank=True, max_length=100)),
                ('horizonte_anos', models.PositiveIntegerField(default=1)),
                ('conhecimento', models.PositiveIntegerField(default=0)),
                ('tolerancia_risco', models.PositiveIntegerField(default=0)),
                ('capacidade_perda', models.PositiveIntegerField(default=0)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_investidor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
